CREATE TABLE Camião (
  Tara             number(5, 2) NOT NULL, 
  Volume           number(5, 2) NOT NULL, 
  VeículoidVeículo number(10) NOT NULL);

CREATE TABLE Carro (
  Número_de_Cilindros number(1) NOT NULL, 
  VeículoidVeículo    number(10) NOT NULL);

CREATE TABLE Classificação (
  Tempo        varchar2(255) NOT NULL, 
  Colocação    number(3) NOT NULL, 
  EquipaCódigo char(9) NOT NULL, 
  ProvaIdAno   nvarchar2(6) NOT NULL);

CREATE TABLE Equipa (
  Código        char(9) NOT NULL, 
  Nome          varchar2(255) NOT NULL, 
  Nacionalidade varchar2(255) NOT NULL, 
  TipoidTipo    char(2) NOT NULL, 
  ProvaIdAno    nvarchar2(6) NOT NULL, 
  PRIMARY KEY (Código));

CREATE TABLE Equipa_Etapa (
  EquipaCódigo char(9) NOT NULL, 
  EtapaidEtapa number(10) NOT NULL, 
  Tempo        varchar2(255) NOT NULL, 
  Colocação    number(3) NOT NULL, 
  PRIMARY KEY (EquipaCódigo, 
  EtapaidEtapa));

CREATE TABLE Equipa_Penalização (
  EquipaCódigo             char(9) NOT NULL, 
  PenalizaçãoidPenalização number(10) NOT NULL, 
  EtapaidEtapa             number(10) NOT NULL, 
  PRIMARY KEY (EquipaCódigo, 
  PenalizaçãoidPenalização));

CREATE TABLE Etapa (
  idEtapa         number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Data_início     date NOT NULL, 
  Local_início    varchar2(255) NOT NULL, 
  Data_fim        date NOT NULL, 
  Local_fim       varchar2(255) NOT NULL, 
  Número_da_etapa number NOT NULL, 
  PRIMARY KEY (idEtapa));

CREATE TABLE Etapa_Troço (
  TroçoidTroço number(10) NOT NULL, 
  EtapaidEtapa number(10) NOT NULL, 
  PRIMARY KEY (TroçoidTroço, 
  EtapaidEtapa));

CREATE TABLE Penalização (
  idPenalização number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Tipo          varchar2(255) NOT NULL, 
  Tempo         varchar2(255) NOT NULL, 
  PRIMARY KEY (idPenalização));

CREATE TABLE Piloto (
  Telefone                  varchar2(255) NOT NULL, 
  Email                     varchar2(255) NOT NULL, 
  Nacionalidade             varchar2(255) NOT NULL, 
  EquipaCódigo              char(9) NOT NULL, 
  "Tipo PilotoidTipoPiloto" number(10) NOT NULL, 
  PRIMARY KEY (Telefone, 
  Email));

CREATE TABLE Prova (
  idProva    nvarchar2(6) NOT NULL, 
  Ano        number(4) NOT NULL, 
  TipoidTipo char(2) NOT NULL, 
  PRIMARY KEY (idProva));

CREATE TABLE Prova_Etapa (
  ProvaIdAno   nvarchar2(6) NOT NULL, 
  EtapaidEtapa number(10) NOT NULL, 
  PRIMARY KEY (ProvaIdAno, 
  EtapaidEtapa));

CREATE TABLE "Tipo Piloto" (
  idTipoPiloto number(10) GENERATED BY DEFAULT AS IDENTITY, 
  TipoDeCargo  varchar2(255) NOT NULL, 
  PRIMARY KEY (idTipoPiloto));

CREATE TABLE TipoVeiculo (
  idTipoVeiculo char(2) NOT NULL, 
  PRIMARY KEY (idTipoVeiculo));

CREATE TABLE Troço (
  idTroço                      number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Local_ínicio                 varchar2(255) NOT NULL, 
  Local_fim                    varchar2(255) NOT NULL, 
  Distância                    number(7, 2) NOT NULL, 
  "Tipo de TroçoidTipoDeTroço" number(10) NOT NULL, 
  PRIMARY KEY (idTroço));

CREATE TABLE Troço_Cronometrado (
  Tempo        varchar2(255) NOT NULL, 
  TroçoidTroço number(10) NOT NULL);

CREATE TABLE Troço_Não_Cronometrado (
  Colocação    number(3) NOT NULL, 
  TroçoidTroço number(10) NOT NULL);

CREATE TABLE Veículo (
  idVeículo    number(10) GENERATED BY DEFAULT AS IDENTITY, 
  Marca        varchar2(255) NOT NULL, 
  Modelo       varchar2(255) NOT NULL, 
  Cilindrada   number(6, 3) NOT NULL, 
  Combustível  varchar2(255) NOT NULL, 
  TipoidTipo   char(2) NOT NULL, 
  EquipaCódigo char(9) NOT NULL, 
  PRIMARY KEY (idVeículo));
  
ALTER TABLE Equipa_Penalização ADD CONSTRAINT FKEquipa_PenIdPen FOREIGN KEY (PenalizaçãoidPenalização) REFERENCES Penalização (idPenalização);
ALTER TABLE Equipa_Penalização ADD CONSTRAINT FKEquipa_PenIdEtapa FOREIGN KEY (EtapaidEtapa) REFERENCES Etapa (idEtapa);
ALTER TABLE Equipa_Penalização ADD CONSTRAINT FKEquipa_PenIdEquipa FOREIGN KEY (EquipaCódigo) REFERENCES Equipa (Código);

ALTER TABLE Prova_Etapa ADD CONSTRAINT FKProva_EtapaIdEtapa FOREIGN KEY (EtapaidEtapa) REFERENCES Etapa (idEtapa);
ALTER TABLE Prova_Etapa ADD CONSTRAINT FKProva_EtapaIdProva FOREIGN KEY (ProvaIdAno) REFERENCES Prova (idProva);

ALTER TABLE Equipa_Etapa ADD CONSTRAINT FKEquipa_EtapaIdEtapa FOREIGN KEY (EtapaidEtapa) REFERENCES Etapa (idEtapa);
ALTER TABLE Equipa_Etapa ADD CONSTRAINT FKEquipa_EtapaIdEquipa FOREIGN KEY (EquipaCódigo) REFERENCES Equipa (Código);

ALTER TABLE Etapa_Troço ADD CONSTRAINT FKEtapa_TroçoIdEtapa FOREIGN KEY (EtapaidEtapa) REFERENCES Etapa (idEtapa);
ALTER TABLE Etapa_Troço ADD CONSTRAINT FKEtapa_TroçoIdTroço FOREIGN KEY (TroçoidTroço) REFERENCES Troço (idTroço);

ALTER TABLE Camião ADD CONSTRAINT FKCamião FOREIGN KEY (VeículoidVeículo) REFERENCES Veículo (idVeículo);
 

ALTER TABLE Carro ADD CONSTRAINT FKCarro FOREIGN KEY (VeículoidVeículo) REFERENCES Veículo (idVeículo);
ALTER TABLE Carro ADD CONSTRAINT NrCilindros CHECK (Número_de_Cilindros >= 2 AND Número_de_Cilindros <= 6);

ALTER TABLE Veículo ADD CONSTRAINT FKVeículoIdTipo FOREIGN KEY (TipoidTipo) REFERENCES TipoVeiculo (idTipoVeiculo);
ALTER TABLE Veículo ADD CONSTRAINT FKVeículoIdEquipa FOREIGN KEY (EquipaCódigo) REFERENCES Equipa (Código);
ALTER TABLE Veículo ADD CONSTRAINT CkTipoCorrespondente CHECK ((TipoidTipo LIKE 'BK' AND EquipaCódigo LIKE '____BK___') OR (TipoidTipo LIKE 'CR' AND EquipaCódigo LIKE '____CR___') OR (TipoidTipo LIKE 'TR' AND EquipaCódigo LIKE '____TR___')); 

ALTER TABLE Piloto ADD CONSTRAINT FKPilotoIdPiloto FOREIGN KEY ("Tipo PilotoidTipoPiloto") REFERENCES "Tipo Piloto" (idTipoPiloto);
ALTER TABLE Piloto ADD CONSTRAINT FKPilotoIdEquipa FOREIGN KEY (EquipaCódigo) REFERENCES Equipa (Código);

ALTER TABLE Equipa ADD CONSTRAINT FKEquipaIdTipo FOREIGN KEY (TipoidTipo) REFERENCES TipoVeiculo (idTipoVeiculo);
ALTER TABLE Equipa ADD CONSTRAINT FKEquipaIdProva FOREIGN KEY (ProvaIdAno) REFERENCES Prova (idProva);
ALTER TABLE Equipa ADD CONSTRAINT CkCodTipo CHECK ((Código LIKE '____BK___'  AND TipoidTipo LIKE 'BK') OR (Código LIKE '____CR___'  AND TipoidTipo LIKE 'CR') OR (Código LIKE '____TR___'  AND TipoidTipo LIKE 'TR')  );

ALTER TABLE Prova ADD CONSTRAINT FKProva FOREIGN KEY (TipoidTipo) REFERENCES TipoVeiculo (idTipoVeiculo);

ALTER TABLE Classificação ADD CONSTRAINT FKClassificIdEquipa FOREIGN KEY (EquipaCódigo) REFERENCES Equipa (Código);
ALTER TABLE Classificação ADD CONSTRAINT FKClassificIdProva FOREIGN KEY (ProvaIdAno) REFERENCES Prova (idProva);

ALTER TABLE Troço_Não_Cronometrado ADD CONSTRAINT FKTroçoNC FOREIGN KEY (TroçoidTroço) REFERENCES Troço (idTroço);

ALTER TABLE Troço_Cronometrado ADD CONSTRAINT FKTroçoC FOREIGN KEY (TroçoidTroço) REFERENCES Troço (idTroço);

ALTER TABLE TipoVeiculo  ADD CONSTRAINT CkTipo CHECK (idTipoVeiculo='BK' OR idTipoVeiculo='CR' OR idTipoVeiculo='TR');


